In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np

In [3]:
model=Sequential()
model.add(Conv2D(filters=16,kernel_size=2,padding='same',activation='relu',input_shape=(224,224,3)))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=32,kernel_size=2,padding='same',activation='relu'))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=64,kernel_size=2,padding='same',activation='relu'))
model.add(MaxPooling2D(pool_size=2))
model.add(Flatten())
model.add(Dense(500, activation='relu'))
model.add(Dense(2,activation='softmax'))


In [4]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [5]:
train_datagen = ImageDataGenerator(rescale=1./255,shear_range = 0.2, zoom_range=0.2, horizontal_flip=True)

In [6]:
test_datagen=ImageDataGenerator(rescale=1./255)

In [7]:
training_set=train_datagen.flow_from_directory('C:/Users/sameer/Downloads/Dataset/Dataset/Train',target_size=(224,224),batch_size=32,class_mode='categorical')

Found 416 images belonging to 2 classes.


In [9]:
test_set=test_datagen.flow_from_directory('C:/Users/sameer/Downloads/Dataset/Dataset/Test',target_size=(224,224),batch_size=32,class_mode='categorical')

Found 134 images belonging to 2 classes.


In [11]:
r=model.fit(training_set, validation_data=test_set,epochs=5,steps_per_epoch=len(training_set),validation_steps=len(test_set))

Epoch 1/5
13/13 [==============================] - 15s 1s/step - loss: 0.6712 - accuracy: 0.6298 - val_loss: 0.6632 - val_accuracy: 0.6791
Epoch 2/5
13/13 [==============================] - 16s 1s/step - loss: 0.6139 - accuracy: 0.6538 - val_loss: 0.8160 - val_accuracy: 0.3657
Epoch 3/5
13/13 [==============================] - 32s 2s/step - loss: 0.5318 - accuracy: 0.7548 - val_loss: 0.8966 - val_accuracy: 0.5970
Epoch 4/5
13/13 [==============================] - 27s 2s/step - loss: 0.4681 - accuracy: 0.7620 - val_loss: 1.0971 - val_accuracy: 0.3209
Epoch 5/5
13/13 [==============================] - 34s 3s/step - loss: 0.4549 - accuracy: 0.7909 - val_loss: 0.8045 - val_accuracy: 0.5075


In [12]:
y_pred=model.predict(test_set)  #since we have used two nodes therefore we get values and summation of them will be one

In [13]:
y_pred    #higher value on left side means it is parasitic and low values on right side means it is not parasitic.

array([[0.3948118 , 0.6051882 ],
       [0.80713314, 0.19286688],
       [0.4821968 , 0.51780325],
       [0.45109886, 0.54890114],
       [0.80895543, 0.19104455],
       [0.63311464, 0.36688542],
       [0.82059836, 0.17940159],
       [0.84707147, 0.15292856],
       [0.64581347, 0.35418653],
       [0.84533685, 0.15466313],
       [0.7574896 , 0.24251042],
       [0.8711175 , 0.12888248],
       [0.4704107 , 0.5295893 ],
       [0.717091  , 0.28290898],
       [0.53621566, 0.4637844 ],
       [0.8614354 , 0.1385646 ],
       [0.5894278 , 0.4105722 ],
       [0.7312236 , 0.26877642],
       [0.9628162 , 0.03718384],
       [0.5244828 , 0.47551724],
       [0.47352767, 0.52647233],
       [0.83907276, 0.16092722],
       [0.5700936 , 0.42990637],
       [0.62522334, 0.37477663],
       [0.8172881 , 0.18271196],
       [0.55941445, 0.4405855 ],
       [0.86686736, 0.13313256],
       [0.45719764, 0.5428024 ],
       [0.8108076 , 0.18919241],
       [0.85615826, 0.14384168],
       [0.

In [14]:
#above, whcihever wil be the highest value, we will have to take that index (0 or 1) so we use argmax for that

In [15]:
y_pred=np.argmax(y_pred,axis=1)  #argmax helps to get the index of the maximum number in tht row of array

In [16]:
y_pred    #0 indicates the person is infected and 1 opposite

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0], dtype=int64)

# Now lets read the image and predict whether it is infected or not

In [17]:
from tensorflow.keras.preprocessing import image

In [21]:
img=image.load_img('C:/Users/sameer/Downloads/Dataset/Dataset/Test/Uninfected/2.png',target_size=(224,224))

In [22]:
x=image.img_to_array(img)
x

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [23]:
x.shape

(224, 224, 3)

In [24]:
x=x/255

In [27]:
from tensorflow.keras.applications.resnet50 import preprocess_input

In [28]:
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape

(1, 1, 224, 224, 3)